### PR TITLE
Add optional endpoint_url to s3 keywords

### PR DESCRIPTION
**Pull request by Jakob-em**
These changes make it possible to use an s3 mock implementaion like https://hub.docker.com/r/adobe/s3mock

### CODE REVIEW

**Comment by Jakob-em** [comment]
@teaglebuilt Would it be possbile to get this merged?

**Comment by Jakob-em** [comment]
@teaglebuilt Is there anything wrong with the PR? Could you please give me more information why this can't be merged?

**Review by adrianyorke — COMMENTED** [review]
If you remove region then existing test automation scripts may fail.

**Comment by teaglebuilt** [comment]
@adrianyorke @Jakob-em is this ready to be merged?

**Comment by Jakob-em** [comment]
@teaglebuilt I added the `region` parameter back to keep the compatibility with existing scripts.
Would be happy to get this merged 🙂

**Comment by adrianyorke** [comment]
Thanks for the PR and region fix @Jakob-em.

**Comment by iampluque** [comment]
@Jakob-em do you plan a release with this PR ?

**Pull request merged**
