### PR TITLE
fix for key should not exist

### PR DESCRIPTION
**Pull request by teaglebuilt**
One thing I have thought of from this issue is taking the client error response into the exceptions class and dismantling the response object and formatted for the user.

The fix for this keyword is obvious and was something I obviously missed in a rush. I did not test it extensively. a robot test has been added, unit test is not complete.

### CODE REVIEW

**Comment by adrianyorke** [comment]
I notice you are using f-strings (which is great) but this means the library no longer support Python 2 or Python 3 version before 3.6.  Is this intended?

**Review by adrianyorke — CHANGES_REQUESTED** [review]
Thanks for this PR. I notice you are using f-strings (which is great) but this means the library no longer supports Python 2 or Python 3 version before 3.6. Is this intended?

PEP8 recommends leaving a blank line at the end of .py files, I think that's why there is a strange "no entry" symbol.  Suggestion: just hit enter on the final line then a blank line will appear and there will be no more warning.

What does "# noqa" indicate in s3.py?

Only need a single line spacing is normally used between sections in .robot files, you have 2 or 3 in places.

"Variables" section assignments do not require "=" so this is fine for example:
*** Variables ***
${REGION}  us-east-1
${BUCKET}  zappastaticbin
${KEY}  path_test.html

**Comment by teaglebuilt** [comment]
your right, we need to make sure this library is compatible for both versions. As far as # noqa in s3. I believe i can get rid of that. We might need to open an issue to tighten up on linting and any other configurations that might be misconfigured. 

ill update this pr

**Review by adrianyorke — APPROVED** [review]
Thanks, looks good.

**Comment by adrianyorke** [comment]
Merged.

**Pull request merged**
